stages:
  - docker
services:
  - docker:dind
docker-job:
  stage: docker
  image: docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t registry.gitlab.com/hchoi36/seniorproject .
    - docker push registry.gitlab.com/hchoi36/seniorproject
